### ISSUE TITLE
Unable to use on Heroku CI

### ISSUE THREAD

**Issue by IanVaughan** [grodowski/undercover#102]
I'm not sure if I'm doing something wrong, but it doesn't look like a Heroku CI build dyno contains a copy of the `.git` repo.
As such there is no way for this tool to check against that and run correctly, am I correct?

I posted a more generic question attempting to double-check Heroku CI dyno here https://stackoverflow.com/questions/62377009/how-can-i-access-git-files-on-a-heroku-ci-dyno

**Comment by grodowski** [comment]
Hi @IanVaughan and apologies for apparently ignoring this issue for so long.  Have you found a solution?

**Comment by IanVaughan** [comment]
Hiya, no we didn't, I don't think it's possible to fix due to the way Heroku builds the slug.
In the end we switched (was planning to anyway) to GitHub actions, and it works great on that!
