### ISSUE TITLE
Does not find uncovered sinatra routes

### ISSUE THREAD

**Issue by antondalgren** [grodowski/undercover#135]
Undercover does not find this uncovered sinatra route:
```ruby
get '/dummy_path' do
  puts "This line is not covered"
end
```
`git diff master`:
```diff
+    get '/dummy_path' do
+      puts "This line is not covered"
+    end
```
`undercover -c master`:
```
undercover: ✅ No coverage is missing in latest changes
Undercover finished in 0.0505s
```

simplecov HTML formatter output:
![image](https://user-images.githubusercontent.com/9164583/107489905-786c7f00-6b89-11eb-9803-4cbd88015904.png)

**Comment by grodowski** [comment]
@antondalgren hi and thanks for reporting! There's a known edge-cases that might or may not be related to this: #83. Can you include a sample file that shows this behaviour? I'll look into it
