### ISSUE TITLE
Loosen requirement on rugged ?

### ISSUE THREAD

**Issue by kuahyeow** [grodowski/undercover#160]
Is it possible to loosen the gem version requirement for rugged ? We are currently using the 1.2.0 version of rugged.

Maybe it's possible to use ` < 2.0`, similar to https://rubygems.org/gems/licensee ?

**Comment by kuahyeow** [comment]
Oh this was already done in https://github.com/grodowski/undercover/blob/master/undercover.gemspec#L30. @grodowski, is it possible to publish a new version of the gem ?

**Comment by grodowski** [comment]
Thanks for bringing this up @kuahyeow, pushing a new tag soon!

**Comment by kuahyeow** [comment]
Thanks ! Looking forward to using this in GitLab (see https://gitlab.com/gitlab-org/gitlab/-/merge_requests/74859)

**Comment by grodowski** [comment]
Done and included in `0.4.4`. Thanks for reporting @kuahyeow
