### ISSUE TITLE
One-line update is not being recognized

### ISSUE THREAD

**Issue by lizhangyuh** [grodowski/undercover#204]
https://github.com/grodowski/undercover/blob/a5a26c19689f531a2e562042101f4e1d9427bd40/lib/undercover/result.rb#L16

I came across an issue where, if I update just one line block in a file, the `first_line` and `last_line` of the `Result` are the same, and the `@coverage` becomes an empty array.

Is this intentional? If so, could you please explain the reasoning behind it? Thanks!

**Comment by grodowski** [comment]
Hi @lizhangyuh! Thank you for submitting the issue. Looks wrong and thus I'll try to reproduce in a test case and fix. If you'd be keen to submit a PR that would be great too.

**Comment by lizhangyuh** [comment]
> Hi @lizhangyuh! Thank you for submitting the issue. Looks wrong and thus I'll try to reproduce in a test case and fix. If you'd be keen to submit a PR that would be great too.

Thanks for your reply. I will submit a PR for this.
