### ISSUE TITLE
Ruby 3.3.0 - Add bigdecimal into gemspec

### ISSUE THREAD

**Issue by Laykou** [grodowski/undercover#205]
Running this in Ruby 3.3.0 I received following error

warning: bigdecimal was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add bigdecimal to your Gemfile or gemspec. Also contact author of undercover-0.4.5 to add bigdecimal into its gemspec.

**Comment by grodowski** [comment]
Thanks @Laykou, I will be releasing a 3.3.0 update soon (~this week)
