### ISSUE TITLE
Migration in schema.rb being flagged as not covered in 0.6.1

### ISSUE THREAD

**Issue by dinjas** [grodowski/undercover#217]
We started getting this error in one of our Rails applications after upgrading from `0.5.0` to `0.6.1`:

```
Successfully installed undercover-0.6.1
6 gems installed
undercover: 👮‍♂️ some methods have no test coverage! Please add specs for methods listed below
🚨 1) node `block (t)` type: block,
      loc: db/schema.rb:307:316, coverage: 0.0%
307:   create_table "friendly_id_slugs", force: :cascade do |t| hits: n/a
308:     t.string "slug", null: false hits: n/a
309:     t.integer "sluggable_id", null: false hits: n/a
310:     t.string "sluggable_type", limit: 50 hits: n/a
311:     t.string "scope" hits: n/a
312:     t.datetime "created_at" hits: n/a
313:     t.index ["slug", "sluggable_type", "scope"], name: "index_friendly_id_slugs_on_slug_and_sluggable_type_and_scope", unique: true hits: n/a
314:     t.index ["slug", "sluggable_type"], name: "index_friendly_id_slugs_on_slug_and_sluggable_type" hits: n/a
315:     t.index ["sluggable_type", "sluggable_id"], name: "index_friendly_id_slugs_on_sluggable_type_and_sluggable_id" hits: n/a
316:   end hits: n/a
Undercover finished in 0.4356s
```

That particular app uses the [`friendly_id` gem](https://github.com/norman/friendly_id), though I don't know how relevant that is.

I tried adding a filter to ignore the `db/` directory to our Simplecov config, but it didn't seem to make a difference.

E.g.:
```
SimpleCov.start do
  add_filter(%r{^/db/})
  ...
```

Undercover in our CI is invoked like this:

```
gem install undercover
undercover --compare origin/main
```

**Comment by grodowski** [comment]
Hey @dinjas! I had an idea to report files in the diff that SimpleCov does not see when they're not required in tests. That got to `0.6.0` ([v0.6.0 release note](https://github.com/grodowski/undercover/releases/tag/v0.6.0)). 

However, this introduced two problems:
- for files not required by SimpleCov, SimpleCov's ignores are not respected
- requires additional (and duplicate) configs, which I added ([docs](https://github.com/grodowski/undercover?tab=readme-ov-file#cli-options)) and will also be adding to UndercoverCI, the GitHub app. But maybe it's time to re-think this and only enable the "extended diff scope" as an option, not sure how it would be called.


As a short-term fix, I am adding `db/` to the [exclude defaults](https://github.com/grodowski/undercover/blob/258e345c418be36e91718b2ee240c228c8c6267f/lib/undercover/options.rb#L20-L21) and releasing a new patch release.

**Comment by dinjas** [comment]
@grodowski Hi, thank you for that! I completely missed the release notes, that would have been a great place for me to start 🤦.
I can confirm `0.6.2` resolved the issue for us. 
Thanks for the tool you're providing here, it's appreciated!
Feel free to close this or leave it open, It's resolved from my perspective. 😀
