### ISSUE TITLE
Branch coverage

### ISSUE THREAD

**Issue by grodowski** [grodowski/undercover#26]

**Comment by GCorbel** [comment]
Hello,

@drdrsh created this MR : https://github.com/fortissimo1997/simplecov-lcov/pull/24 which adds the support of branch coverage for simplecov-lcov. 

Is this issue closed because this feature was missing?

**Comment by grodowski** [comment]
Thanks for bringing this up @GCorbel! Adding branch coverage to undercover would be 💯. I closed this one as unrealistic given my limited time budget, but the added support in simplecov makes it much more feasible today.

**Comment by grodowski** [comment]
@GCorbel I released branch coverage with output formatting in `0.4.0` - next step will be adding it to `pronto-undercover` and UndercoverCI.

@magneland thanks for you contribution 🙌
