### ISSUE TITLE
Integrate with GitHub's Checks API

### ISSUE THREAD

**Issue by grodowski** [grodowski/undercover#3]
https://blog.github.com/2018-05-07-introducing-checks-api/

**Comment by dannysmith** [comment]
This would be awesome. I've not worked with the checks API, but happy to help if you know how you want it to work.

**Comment by grodowski** [comment]
Hi Danny! Thanks for your interest in contributing to this gem 🙃 

The idea I had for Checks support involves integrating this gem with `pronto`. `pronto` already supports various [`Formatter`s](https://github.com/prontolabs/pronto/tree/master/lib/pronto/formatter) that can comment on pull requests (among other useful integrations). Implementing checks should be a matter of extending the current formatter interface.

Wrapping up:
- [pronto-undercover](https://github.com/grodowski/pronto-undercover) will run this gem within `pronto run`. That's on my to-do list.
- new formatter like `GithubCheckFormatter < GithubFormatter` could post results to the Checks API using credentials from https://github.com/prontolabs/pronto/blob/d34be4f69bce0941337b4d5917a6211a5b0712b1/lib/pronto/github.rb#L82-L87 

I hope this will give you some starting points if you decide to look at `pronto-undercover`. I have done some initial research but didn't get past initial gem setup in development terms. I am open to discussion about this approach or any other you may have.

**Comment by dannysmith** [comment]
Thought I'd drop a note here to say that I never got round to this and am not likely to do so in the foreseeable.

**Comment by grodowski** [comment]
@dannysmith I've been recently working on a Checks api integration for undercover in a different repo
