### ISSUE TITLE
Support Ruby < 2

### ISSUE THREAD

**Issue by schmijos** [grodowski/undercover#33]
Migrating old projects involves migrating to new versions of Ruby. But I cannot do this without touching project code. Undercover would be the perfect tool here, but I cannot use it, because of [*imagen*](https://github.com/grodowski/imagen_rb)'s dependency. But since *imagen* is also your gem, I guess this is not a problem, right 🤓 ?

![image](https://user-images.githubusercontent.com/245443/43724249-cba6a282-9999-11e8-893b-6b3bc5dcd1de.png)

**Comment by grodowski** [comment]
Thanks for submitting this issue. I didn't think of that use case, sounds good!

Bad news is that `parser` already depends on Ruby 2.0.0+, so running undercover on < 2 seems nontrivial. However, good news is that `parser` itself can parse older ruby syntax versions while running on 2.0.0+. So it will either just work (unlikely), or we need to add a flag like `--target-ruby-version` to the CLI to select the version for `parser` to use.

I have captured the above in https://github.com/grodowski/imagen_rb/issues/7

@schmijos do you think that's a good solution for you?

**Comment by schmijos** [comment]
Sure, that sounds lovely!

**Comment by grodowski** [comment]
@schmijos I started looking into this here https://github.com/grodowski/imagen_rb/pull/26

**Comment by grodowski** [comment]
@schmijos check out `0.2.0` 🙃

**Comment by schmijos** [comment]
Hm… I'm not sure how to use it. I cannot configure _undercover_ in the `spec_helper.rb` directly but I've to call it manually, correct?

The problem is if I switch the ruby version, my repository gets changed because I use _rbenv:_

![image](https://user-images.githubusercontent.com/245443/44665343-f9654980-aa15-11e8-876f-6b4fd0541259.png)
