### ISSUE TITLE
Replace node classes with human types

### ISSUE THREAD

**Issue by grodowski** [grodowski/undercover#4]
Current output of undercover includes class names, like:

```
🚨 5) node `parse` type: Imagen::Node::IMethod,
      loc: lib/undercover/options.rb:34:58,coverage: 69.23%
```

Replace type with a friendly text like "instance method", "class method" or "class". This involves adding a method to subclasses of `Imagen::Node` and displaying it in `Undercover::Formatter`

**Comment by kruszczynski** [comment]
🙋‍♂️
