### ISSUE TITLE
Add a way to ignore coverage checks

### ISSUE THREAD

**Issue by grodowski** [grodowski/undercover#5]
Needs specification, but it would be useful to mark files or parts of them as `nocov`. Could be good to make it an unobtrusive way (external yml file?)

**Comment by adamcohen2** [comment]
@grodowski I've tried using `:nocov:` and it works, but I can't find it documented anywhere - can you point me to the docs which explain how to ignore coverage checks? Thanks!

**Comment by adamcohen2** [comment]
> @grodowski I've tried using `:nocov:` and it works, but I can't find it documented anywhere - can you point me to the docs which explain how to ignore coverage checks? Thanks!

Looks like this has now been documented in the `README` [here](https://github.com/grodowski/undercover/commit/0e33d690a00789ce5cc758aea0dfcfa532dc2be3), thanks!
