### ISSUE TITLE
EncodingError: invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by mergulhao** [grodowski/undercover#54]
Hi @grodowski 

I got the following problem when tried to use undercover... Any thought where should I start to fix this? 👇 

<img width="860" alt="Screen Shot 2019-04-02 at 10 57 12" src="https://user-images.githubusercontent.com/8128/55408505-7cafc600-5536-11e9-9f52-f0740e4f490c.png">

**Comment by grodowski** [comment]
Hi @mergulhao! Thanks for reporting this problem

This has been seen before and relates to the `parser` gem not being able to parse certain strings. I attempted to fix this with https://github.com/grodowski/undercover/pull/32, which was probably not enough to cover all cases.

This is a related `parser` issue https://github.com/whitequark/parser/issues/323

**Comment by grodowski** [comment]
@mergulhao I've looked into this a bit today. I guess (from the shell prompt) that you're running undercover within docker. Is the system locale set to `en_US.UTF8`?

```
export LC_ALL=C.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
```

**Comment by mergulhao** [comment]
@grodowski I didn't have time to look into this again. I'll try your suggestion and feedback to you probably until the end of this week.

**Comment by mergulhao** [comment]
@grodowski Your guess was correct... I'm running within docker. Those env vars was not set. After set those vars, it worked.

**Comment by grodowski** [comment]
Thanks for leaving a reply @mergulhao. I'm closing this one

**Comment by fabn** [comment]
I was having the same issue in docker, in my case just `export LC_ALL=C.UTF-8` fixed the issue. Thanks anyway

**Comment by darryn02** [comment]
Worked for me @grodowski and @fabn (only needed `LC_ALL`)- thank you!
