### ISSUE TITLE
Characters in file names

### ISSUE THREAD

**Issue by RepoCorp** [grodowski/undercover#57]
I'm working on a project that has some files with scores in the names. The lcov parser is truncating the file names and the process fails when trying to process that file. If I replace the regex to accept any character it works fine. Why is the regex restriction necessary? 

https://github.com/grodowski/undercover/blob/8f9cb32094d1669d67ff957337f95243c4d15ff2/lib/undercover/lcov_parser.rb#L30

**Comment by grodowski** [comment]
Thanks for submitting this issue! The `\w` match is a bug – turns out JS and rust LCOV parsers just match the whole line. Feel free to open a PR (otherwise, I should be able to fix this very soon!).

**Comment by RepoCorp** [comment]
Thanks, @grodowski. I will open the PR.
